// handle the session on the client-side
// making the session available to the UI

// generated by SvelteKit for each endpoint/page
import type { LayoutLoad } from './$types';
import { getSupabase } from '@supabase/auth-helpers-sveltekit';

export const load: LayoutLoad = async (event) => {
    const { session } = await getSupabase(event);
    return { session }
}