name: Build and Setup Workflow
run-name: Setup by ${{ github.actor }}
on:
  push:
    branches-ignore:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Scuffed env setup
        run: |
          touch frontend/.env
          echo "VITE_SUPABASE_URL=${VITE_SUPABASE_URL}" >> frontend/.env
          echo "VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}" >> frontend/.env
        env:
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Install dependencies
        run: cd frontend && npm run test

      #- name: Run tests
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: ./frontend
      #    file: ./frontend/Dockerfile
      #    push: false
      #    target: test

      - name: Build production environment
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          target: prod
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

#      - name: Install Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 19
#
#      - name: Install pnpm
#        uses: pnpm/action-setup@v2.2.4
#        with:
#          version: 7.23.0
#      
#      - name: Install dependencies
#        run: pnpm install
#
#      - name: Backend hello step 
#        id: hello
#        #uses: ./.github/actions
#        uses: ./
#        with:
#          who-to-greet: 'Frontend'
#      - name: Output time of greeting
#        run: echo "Greeting time ${{ steps.hello.outputs.time}}"
